const que1 = "what iss the diffrence between var variable and const variable" 
const ans1 = 'i) we can use variable before instioaling when use var but not for let '
const que2 = "what is diffrecne between undifiend and not defiend" //// undefined a value or not defined a error whch make code stuck throw the error
const que3 = 'What happend when you try to access the variable value before intilizing?'
const que4 = "custom layout in the next js"
const que5 = "how to use loading page into next js"
const que6 = "library or framework me antar"
const que7 = "how object work into the javasctipt "
const que8 = "what is the main porpose to of new keyword in the object orianeted programming language"
